# This is a workflow file for CI/CD will run tests on every push and deploy to Railway on every push to main branch
name: CI/CD

# Trigger the workflow on push or pull request
on: push

jobs:
  # This is the CI (Continuous Integration) job
  # It will run tests on every push
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      # Sets up nodejs environment
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installs all dependencies
      - name: Download deps
        run: npm i

      # Runs all code tests under /tests folder
      - name: Run tests
        run: npm run test
  
  # This is the CD (Continuous Delivery) job
  # It will deploy to Railway on every push to main branch
  CD:
    runs-on: ubuntu-latest
    needs: CI # This job will only run if CI job passes
    # This job will only run if push is to main branch
    if: github.ref == 'refs/heads/main'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setups Railway CLI
      - name: Install Railway
        run: npm i -g @railway/cli

      # Deploys to Railway using Railway CLI
      - name: Deploy to Railway
        run: railway up --service 32f1c913-845d-448e-b089-2d153ab54d8e
        env:
          # This is the Railway token, it is stored in Github Secrets
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
