name: CI/CD

on: push

jobs: 
  CI: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download deps
        run: npm i
    
      - name: Run tests
        run: npm run test
  CD:
    runs-on: ubuntu-latest
    needs: CI  
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Railway
        uses: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service 32f1c913-845d-448e-b089-2d153ab54d8e
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
